### ISSUE TITLE
Exception in previous day rates - 500 Server error in API

### ISSUE THREAD

**Issue by cameronclans** [pulquero/agile-powerwall#5]
Hi, 
I experienced some quirkiness over the last few weeks and so I left HA off overnight and restarted this morning with debug on. I noted the errors below:
```yaml
2024-03-19 04:50:21.217 ERROR (MainThread) [custom_components.pyscript.apps.powerwall.refresh_previous_day_rates] Exception in <apps.powerwall.refresh_previous_day_rates> line 76:
tariff_data=tariff_data
^
HTTPError: 500 Server Error: upstream internal error for url: https://owner-api.teslamotors.com/api/1/energy_sites/*************142/time_of_use_settings
```

It's worth saying that the utility rate plan for import appears to have updated correctly but that export has not (all show 0.00). It's logical that this might relate to the fact that HA was off overnight and therefore previous day rates is throwing an exception because it doesn't have any previous day rates but this is a complete guess on my part. 

Config (unchanged since we got it all working):
```yaml
allow_all_imports: true
apps:
  powerwall:
      email: "le******@******.com"
      refresh_token: "******"
      tariff_name: Tracker
      tariff_provider: Octopus
      import_mpan: "*************"
      export_mpan: "*************"
      tariff_breaks: [0.10, 0.20, 0.30]
#      tariff_breaks: jenks
      import_tariff_pricing: ["average", "average", "maximum", "maximum"]
      export_tariff_pricing: ["average", "average", "maximum", "maximum"]
      plunge_pricing_tariff_breaks: [0.0, 0.10, 0.30] 
```

Thanks in advance
