### ISSUE TITLE
Clarification on Role of Tariff Breakpoints in Time-Based Control

### ISSUE THREAD

**Issue by Nick-Sills** [pulquero/agile-powerwall#7]
Hi,

First of all, thanks for creating this integration—I've been looking for something like this for a while. Now that NetZero is moving to a subscription model for their Agile/Powerwall integration, this project is a very welcome alternative.

Apologies if this isn’t the right place for a question, but I wasn’t sure where else to ask.

I may be mistaken, so please correct me if I’m wrong—but my understanding is that the Powerwall’s time-based control algorithm doesn’t actually use the defined tariff pricing levels (e.g., **Peak, Mid-Peak, Off-Peak, Super Off-Peak**) in its decision-making. Instead, those pricing tiers are mainly for visualization and user input convenience. The Powerwall itself uses the actual time-based tariff values to decide when to charge, discharge, or hold.

If that's correct, then I’m curious—why do the `import_tariff_breaks`, `plunge_pricing_tariff_breaks`, or even the `tariff_pricing` arrays matter from a functional perspective? Are they just for UI interpretation, or does your integration use them in a way that affects Powerwall behavior?

Thanks again for your work on this, and I appreciate any clarification you can offer.

**Comment by pulquero** [comment]
Hi, that's in fact not correct. The powerwall API accepts pricing levels assigned to time-intervals, not actual value amounts. You therefore need to bin the value amounts from Octopus into one of those four pricing levels. The breaks decide how to do the binning. Here is a snippet from the powerwall API that illustrates the point:

```
seasons:
  Summer:
    fromDay: 1
    toDay: 31
    fromMonth: 1
    toMonth: 12
    tou_periods:
      OFF_PEAK:
        - fromDayOfWeek: 0
          toDayOfWeek: 6
          fromHour: 2
          fromMinute: 0
          toHour: 5
          toMinute: 0
      ON_PEAK:
        - fromDayOfWeek: 0
          toDayOfWeek: 6
          fromHour: 16
          fromMinute: 0
          toHour: 19
          toMinute: 0
      PARTIAL_PEAK:
        - fromDayOfWeek: 0
          toDayOfWeek: 6
          fromHour: 0
          fromMinute: 0
          toHour: 2
          toMinute: 0
        - fromDayOfWeek: 0
          toDayOfWeek: 6
          fromHour: 5
          fromMinute: 0
          toHour: 16
          toMinute: 0
        - fromDayOfWeek: 0
          toDayOfWeek: 6
          fromHour: 19
          fromMinute: 0
          toHour: 0
          toMinute: 0
```
